Add maveriknight's custom item
Baystation12/custom-items pull request #142
Opened 2017-10-20 04:10 UTC by HeyBanditoz

[Forum post in question](https://baystation12.net/forums/threads/old-camera-kristen-osterweis-maveriknight.5432/)

2017-10-20 04:17 UTC, HeyBanditoz commented
Is there any way to test these changes?

2017-10-20 17:07 UTC, mustafakalash requested changes
This may require changes to https://github.com/Baystation12/Baystation12/blob/dev/code/modules/paperwork/photography.dm#L164-L171 on the main repo to properly work with the custom icon.

Change `attack_self` to
```dm
on = !on
update_icon()
```
add a `/obj/item/device/camera/update_icon`:
```dm
var/datum/extension/base_icon_state/bis = get_extension(src, /datum/extension/base_icon_state)
if(on)
    icon_state = "[bis.base_icon_state]"
else
    icon_state = "[bis.base_icon_state]_off"
```
Then, add `/obj/item/device/camera/New`:
```dm
set_extension(src, /datum/extension/base_icon_state, /datum/extension/base_icon_state, icon_state)
update_icon()
```
Finally, you're going to want to get an `osterweis_oldcamera_off` with a red light.

Let me know if you have any questions.

2017-10-20 17:07 UTC, mustafakalash commented on config/custom_items.txt
> +req_access: 1
You don't want the `req_access` line.

2017-10-21 00:35 UTC, HeyBanditoz commented
Oh God the spam. Anyway, I think this is ready @mustafakalash if you'd like to check it.

2017-10-21 00:37 UTC, mustafakalash approved these changes
Dependent on Baystation12/Baystation12#19129

2017-10-26 03:27 UTC, merged